config/routes.rb
Rails.application.routes.draw do

  resources :friends
  resources :messages

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'signout', to: 'sessions#destroy'


  root to: 'users#index'
  resources :users do
    resources :inboxes do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_ship.rb
class FriendShip < ApplicationRecord
  # validates :friend_id, you_not_friend
  belongs_to :friend, class_name: "User"
  belongs_to :you, class_name: "User"

  # def you_not_fiend
  #   self.friend_id == self.you_id ? false : true
  # end
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :inbox
  has_many :recipients
  has_many :users, through: :recipients
  # intend to build nested form, first need to config this model
  accepts_nested_attributes_for :recipients
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt

  before_save { self.email = email.downcase }

  has_secure_password

  attr_accessor :remember_token

  has_one :inbox
  has_many :messages, through: :inbox
  has_many :recipients
  has_many :messages, through: :recipients
  has_many :friend_ships, foreign_key: 'you_id',
                          dependent: :destroy

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(remember_token)
    # this is for catch error happen when authenticate forgeted user by other browser
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate, only: [:show, :edit]
  before_action :current_user

  helper_method :current_user, :user_signed_in?

  def authenticate
    # redirect_to sessions_new_path unless user_logged_in?
    redirect_to login_path unless user_logged_in?
  end

  def current_user
    # @current_user ||= User.find_by(session[:user_id])
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def user_logged_in?
    current_user != nil
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if @current_user
      friend = User.find(params[:id])
      @friend = @current_user.friend_ships.new(friend_id: friend.id) if friend
      if @friend.save
        flash[:notice] = "congratulation, you and #{@friend.friend.name} become friend!"
        redirect_to @current_user
      else
        flash[:notice] = "add friend not successfully, try again later!"
        redirect_to 'friends#index'
      end
    end
  end

  def create
  end

end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController

  def index
  end

  def show
    @messages = User.find(params[:user_id]).messages
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    message = Message.find(params[:id])
    if not message.status
      @message = message
      @message.status = true
      @message.read_time = Time.now.utc
      # user cannot readit later if this flag set
      if @message.save
        flash[:notice] = "This message being show only one time"
      end
    else
      flash[:notice] = "This message being removed, you cannot read it"
      redirect_to user_path(@current_user)
    end

  end

  def new
    if user_logged_in?
      @message = @current_user.inbox.messages.new
      @message.recipients.build
      @friends = @current_user.friend_ships
    end
  end

  def create
    if user_logged_in?
      @message = @current_user.inbox.messages.new(message_params)
      if @message.save
        @message.recipients.create(user_id: recipient_params[:recipients])
        flash[:notice] = "message sent successfully"
        redirect_to @current_user
      else
        flash[:notice] = "#{@message.errors.full_messages.to_sentence}"
        render 'new'
      end
    end
  end

  def destroy
  end

  private

  def message_params
    params.require(:message).permit(:subject, :content)
  end

  def recipient_params
     params.require(:message).permit(:recipients)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authenticate, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    # let find user by cookies
    # user = User.find_by(id: cookies.signed[:user_id])
    if user && user.authenticate(session_params[:password])
      flash[:notice] = "logged in successfully"
      log_in user
      remember user
      redirect_to user
    else
      render 'new', flash: "Identity not correct, login again!"
    end
  end

  def destroy
    log_out if user_logged_in?
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      # create inbox for it
      Inbox.create(user: @user)
      redirect_to root_path, notice: "User created successfully"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == @current_user
      @messages = @user.messages.order(created_at: :desc).page(params[:page]).per(10)
      # sent item
      @sent_messages = @user.inbox.messages
    else
      @messages  = nil
      @sent_messages = nil
    end

    @friends = @user.friend_ships

  end

  def index
    current_user
    if params[:page]
      @user = User.page(params[:page]).per(10)
    else
      @user = User.page(1).per(10)
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/create.html.erb
<h1>Friends#create</h1>
<p>Find me in app/views/friends/create.html.erb</p>

app/views/friends/index.html.erb
<br>
<% @users.each do |u| %>
  <div class="card">
    <img class="card-img-top" src="">
      <div class="card-block">
        <h4 class="card-title"><%= u.name %></h4>
        <p class="card-text"><%= u.email %></p>
        <%= link_to "add friend", friend_path(u) %>
      </div>
  </div>
<% end %>

app/views/friends/show.html.erb
<h1>Friends#new</h1>
<p>Find me in app/views/friends/new.html.erb</p>

app/views/inboxes/show.html.erb
<table class="table">
  <tr>
    <th>Status</th>
    <th>Subject</th>
    <th>Sent at</th>
  </tr>
  <% @messages.each do |m| %>
    <tr>
      <td><%= m.status %></td>
      <td><%= m.subject %></td>
      <td><%= m.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ghost chat website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="cointainer-fluid">
      <nav class="navbar navbar-light bg-faded">
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          <a class="navbar-brand" href="/">GHOSTCHAT</a>
          <% if @current_user %>
            <ul class="nav navbar-nav">
                <li class="nav-item">
                  <%= link_to 'Profile', user_path(current_user), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'new message', new_message_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'friends', friends_path, class: "nav-link" %>
                </li>
            </ul>
          <% end %>

          <% if not @current_user %>

          <ul class="nav navbar-nav navbar-right pull-lg-right">
              <li class="nav-item">
                <%= link_to "sign up", signup_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "sign in", login_path, class: "nav-link" %>
              </li>
          </ul>

          <% else %>

          <ul class="nav navbar-nav navbar-right pull-lg-right">
              <li class="nav-item">
                <%= link_to "signout", signout_path, class: "nav-link" %>
              </li>
          </ul>

          <% end %>
        </div>
      </nav>
    </div>

    <p id="notice" style="margin-top:20px;margin-bottom: 20px"><%= notice %></p>

    <br>


    <%= yield %>
</div>





</body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ghostchat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Page 1-1</a></li>
                <li><a href="#">Page 1-2</a></li>
                <li><a href="#">Page 1-3</a></li>
              </ul>
            </li>
            <li><a href="#">Page 2</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        </div>
      </nav>


      <p><%= flash[:notice] %></p>
      <%= yield %>


    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-lg-4">

    <%= form_for(@message, class: "form-group") do |f| %>
      <%= f.label :subject %>
      <%= f.text_field :subject, class: "form-control" %>
      <br>
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>

      <br>
      <%= f.label "Recipient" %>
      <br>
      <% friends_array = @friends.map { |x| [x.friend.name, x.friend_id] } %>
      <%= f.select :recipients, friends_array, class: "form-control" %>

      <br>
      <br>
      <%= f.submit :Send, class: 'btn btn-success' %>

    <% end %>


  </div>
</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/messages/new.html.erb
<br>

<%= render 'form' %>

app/views/messages/show.html.erb
<br>

<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= @message.subject %></h4>
    <p class="card-text"><%= @message.content %></p>
  </div>
</div>

<br>

<%= link_to "Back", user_path(@current_user) %>

app/views/users/create.html.erb
<%= form_for @user do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name , class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email , class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.lable :password %>
		<%= f.password_field :password , class: "form-control" %>
	</div>
<% end %>

app/views/users/index.html.erb
<br>
<h3 class="jumbotron">we just live once, our messages too</h3>
<br>


<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Member at</th>
  </tr>
  <% @user.each do |u| %>
  <tr>
    <td><%= u.name %></td>
    <td><%= u.email %></td>
    <td><%= u.created_at %></td>
  </tr>
  <% end %>
</table>
<%= paginate @user %>

<br>
<br>

app/views/users/new.html.erb
<div class="col-lg-4">

  <h1>Create new user</h1>
  <br>

  <%= form_for(@user, class: "form-group") do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>

    <br>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>

    <br>
    <%= f.submit "create new user"%>
  <% end %>
</div>

app/views/users/show.html.erb
<% if  @messages and @sent_messages %>
<br>
<h3 class="jumbotron"><%="#{@user.name} 's home page"%></h3>
<br>


<h3>Your inbox</h3>
<br>

<table class="table">
  <tr>
    <th>From</th>
    <th>Subject</th>
    <th>Read at</th>
    <th>Received at</th>
  </tr>

  <% @messages.each do |m| %>
    <tr>
      <td><%= link_to m.inbox.user.name, user_path(m.inbox.user) %></td>
          <% if m.status %>
      <td><%= m.subject %></td>
          <% else %>
      <td><%= link_to m.subject, message_path(m) %></td>
          <% end %>
      <td><%= m.status ? "#{m.read_time}" : "Unread" %></td>
      <td><%= m.created_at %></td>
    </tr>
  <% end %>
</table>

<br>
<h3>Sent items</h3>
<br>
<table class="table">
  <tr>
    <th>Subject</th>
    <th>Read at</th>
    <th>Sent at</th>
  </tr>

  <% @sent_messages.each do |s| %>
    <tr>
      <td><%= s.subject %></td>
      <td><%= s.status ? "#{s.read_time}" : "Unread" %></td>
      <td><%= s.created_at %></td>
    </tr>
  <% end %>
</table>

<% else %>
  <br>
  <h3 class="jumbotron"><%="Welcome to #{@user.name} 's home page"%></h3>
  <br>
<% end %>

<br>
<h3><%="#{@user.name}'s friends"%></h3>
<br>
<table class="table">
  <tr>
    <th>name</th>
    <th>email</th>
  </tr>
  <% @friends.each do |x| %>
    <tr>
      <th><%= x.friend.name %></th>
      <th><%= x.friend.email %></th>
    </tr>
  <% end %>
</table>